name: Deploy Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    uses: ./.github/workflows/trivy.yml   # call the trivy workflow

  deploy:
    runs-on: ubuntu-latest
    needs: security-scan   # wait until trivy passes

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/myapp:latest
          docker tag myapp:latest $IMAGE
          docker push $IMAGE
