name: Deploy Application

on:
  push:
    branches: [ main ]
  workflow_dispatch: # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Example: Push to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/myapp:latest
          docker tag myapp:latest $IMAGE
          docker push $IMAGE
